import "./styles/globals.scss";
import "react-toastify/dist/ReactToastify.css";
import { Inter } from "next/font/google";
import Providers from "./provider";
import Head from "next/head";
import Side_bar from "./components/Side_bar";
import Loader from "./components/Loader";
import { Suspense } from "react";
const inter = Inter({ subsets: ["latin"] });
import Footer from "./components/Footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css"
          rel="stylesheet"
        />
      </Head>
      <body className={inter.className}>
        <Suspense fallback={<Loader />}>
          <Providers>
            <Side_bar />
            {children}
          </Providers>
        </Suspense>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"></script>
      </body>
    </html>
  );
}
